# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import synthos_pb2 as proto_dot_synthos__pb2


class ValidationEngineStub(object):
    """============================================================================
    Validation Engine Service
    Handles diversity analysis, cascade training, and predictions
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeDiversity = channel.unary_unary(
                '/synthos.ValidationEngine/AnalyzeDiversity',
                request_serializer=proto_dot_synthos__pb2.DiversityRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.DiversityResponse.FromString,
                )
        self.PreScreenRisk = channel.unary_unary(
                '/synthos.ValidationEngine/PreScreenRisk',
                request_serializer=proto_dot_synthos__pb2.PreScreenRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.PreScreenResponse.FromString,
                )
        self.TrainCascade = channel.unary_stream(
                '/synthos.ValidationEngine/TrainCascade',
                request_serializer=proto_dot_synthos__pb2.CascadeRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.CascadeProgress.FromString,
                )
        self.GetPredictions = channel.unary_unary(
                '/synthos.ValidationEngine/GetPredictions',
                request_serializer=proto_dot_synthos__pb2.PredictionRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.PredictionResponse.FromString,
                )


class ValidationEngineServicer(object):
    """============================================================================
    Validation Engine Service
    Handles diversity analysis, cascade training, and predictions
    ============================================================================

    """

    def AnalyzeDiversity(self, request, context):
        """Phase 2: Analyze diversity and create stratified sample
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreScreenRisk(self, request, context):
        """Phase 3: Pre-screen against collapse signature library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainCascade(self, request, context):
        """Phase 4: Multi-scale cascade training (STREAMING every 10s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictions(self, request, context):
        """Phase 5: Get final predictions with confidence intervals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeDiversity': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDiversity,
                    request_deserializer=proto_dot_synthos__pb2.DiversityRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.DiversityResponse.SerializeToString,
            ),
            'PreScreenRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.PreScreenRisk,
                    request_deserializer=proto_dot_synthos__pb2.PreScreenRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.PreScreenResponse.SerializeToString,
            ),
            'TrainCascade': grpc.unary_stream_rpc_method_handler(
                    servicer.TrainCascade,
                    request_deserializer=proto_dot_synthos__pb2.CascadeRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.CascadeProgress.SerializeToString,
            ),
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=proto_dot_synthos__pb2.PredictionRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synthos.ValidationEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidationEngine(object):
    """============================================================================
    Validation Engine Service
    Handles diversity analysis, cascade training, and predictions
    ============================================================================

    """

    @staticmethod
    def AnalyzeDiversity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.ValidationEngine/AnalyzeDiversity',
            proto_dot_synthos__pb2.DiversityRequest.SerializeToString,
            proto_dot_synthos__pb2.DiversityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PreScreenRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.ValidationEngine/PreScreenRisk',
            proto_dot_synthos__pb2.PreScreenRequest.SerializeToString,
            proto_dot_synthos__pb2.PreScreenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainCascade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/synthos.ValidationEngine/TrainCascade',
            proto_dot_synthos__pb2.CascadeRequest.SerializeToString,
            proto_dot_synthos__pb2.CascadeProgress.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.ValidationEngine/GetPredictions',
            proto_dot_synthos__pb2.PredictionRequest.SerializeToString,
            proto_dot_synthos__pb2.PredictionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CollapseEngineStub(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection, localization, and recommendations
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectCollapse = channel.unary_unary(
                '/synthos.CollapseEngine/DetectCollapse',
                request_serializer=proto_dot_synthos__pb2.CollapseRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.CollapseResponse.FromString,
                )
        self.LocalizeProblems = channel.unary_unary(
                '/synthos.CollapseEngine/LocalizeProblems',
                request_serializer=proto_dot_synthos__pb2.LocalizationRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.LocalizationResponse.FromString,
                )
        self.GenerateRecommendations = channel.unary_unary(
                '/synthos.CollapseEngine/GenerateRecommendations',
                request_serializer=proto_dot_synthos__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=proto_dot_synthos__pb2.RecommendationResponse.FromString,
                )


class CollapseEngineServicer(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection, localization, and recommendations
    ============================================================================

    """

    def DetectCollapse(self, request, context):
        """Phase 5: Detect collapse in cascade results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalizeProblems(self, request, context):
        """Phase 6: Pinpoint problematic data regions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRecommendations(self, request, context):
        """Phase 6: Generate actionable recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollapseEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectCollapse': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCollapse,
                    request_deserializer=proto_dot_synthos__pb2.CollapseRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.CollapseResponse.SerializeToString,
            ),
            'LocalizeProblems': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalizeProblems,
                    request_deserializer=proto_dot_synthos__pb2.LocalizationRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.LocalizationResponse.SerializeToString,
            ),
            'GenerateRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRecommendations,
                    request_deserializer=proto_dot_synthos__pb2.RecommendationRequest.FromString,
                    response_serializer=proto_dot_synthos__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synthos.CollapseEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CollapseEngine(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection, localization, and recommendations
    ============================================================================

    """

    @staticmethod
    def DetectCollapse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.CollapseEngine/DetectCollapse',
            proto_dot_synthos__pb2.CollapseRequest.SerializeToString,
            proto_dot_synthos__pb2.CollapseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LocalizeProblems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.CollapseEngine/LocalizeProblems',
            proto_dot_synthos__pb2.LocalizationRequest.SerializeToString,
            proto_dot_synthos__pb2.LocalizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/synthos.CollapseEngine/GenerateRecommendations',
            proto_dot_synthos__pb2.RecommendationRequest.SerializeToString,
            proto_dot_synthos__pb2.RecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
